# Generated by Django 6.0.2 on 2026-03-06 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activity',
            new_name='analytics_a_timesta_c57384_idx',
            old_name='analytics_a_timesta_0a1f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='analytics_a_course__214647_idx',
            old_name='analytics_a_course__e0e0b4_idx',
        ),
    ]
