# Generated by Django 4.2.27 on 2026-03-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_attachments_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_teachers_attachments/'),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
