# Generated by Django 6.0.2 on 2026-03-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='presence',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('AWAY', 'Away'), ('OFFLINE', 'Offline')], default='PRESENT', help_text='User-set status visible to others (Present / Away / Offline).', max_length=10),
        ),
    ]
