# Generated by Django 6.0.2 on 2026-03-03 01:01

from django.db import migrations, models


def presence_present_to_available(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(presence='PRESENT').update(presence='AVAILABLE')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_text',
            field=models.CharField(blank=True, default='', help_text='Short status message (e.g. Studying now, Taking a break, Listening to Music).', max_length=150),
        ),
        migrations.RunPython(presence_present_to_available, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='presence',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ONLINE', 'Online'), ('AWAY', 'Away'), ('OFFLINE', 'Offline')], default='AVAILABLE', help_text='User-set status visible to others (Available / Online / Away / Offline).', max_length=10),
        ),
    ]
