# Generated by Django 6.0.2 on 2026-03-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_presence_status_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_clear_after',
            field=models.CharField(choices=[('NEVER', 'Never'), ('1H', '1 hour'), ('5H', '5 hours'), ('TODAY', 'Today'), ('WEEK', 'This week')], default='NEVER', help_text='When to clear the custom status message.', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='status_expires_at',
            field=models.DateTimeField(blank=True, help_text='Automatically derived from clear-after choice; when reached, the status message is cleared.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='presence',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('DND', 'Do not disturb'), ('BRB', 'Be right back'), ('AWAY', 'Away'), ('OFFLINE', 'Offline')], default='AVAILABLE', help_text='User-set availability (Available / Busy / DND / BRB / Away / Offline).', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='status_text',
            field=models.CharField(blank=True, default='', help_text='Short status message (e.g. Studying now, Taking a break, Listening to Music).', max_length=200),
        ),
    ]
