# Generated by Django 4.2.27 on 2026-03-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_simplify_presence_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="presence",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("ONLINE", "Online"),
                    ("BUSY", "Busy"),
                    ("AWAY", "Away"),
                    ("OFFLINE", "Offline"),
                ],
                default="AVAILABLE",
                help_text="User-set availability (Available / Online / Busy / Away / Offline).",
                max_length=10,
            ),
        ),
    ]
