# Generated by Django 4.2.27 on 2026-03-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_user_presence"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional address or city/country information.",
                max_length=255,
            ),
        ),
    ]
