# Generated by Django 4.2.27 on 2026-03-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_user_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("EN", "English"), ("DE", "German"), ("OTHER", "Other")],
                default="EN",
                help_text="Preferred language for the interface.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="theme_mode",
            field=models.CharField(
                choices=[("LIGHT", "Light"), ("DARK", "Dark"), ("SYSTEM", "System")],
                default="SYSTEM",
                help_text="Preferred app theme mode.",
                max_length=10,
            ),
        ),
    ]
