# Generated by Django 4.2.27 on 2026-03-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_user_preferred_language_user_theme_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notify_email",
            field=models.BooleanField(
                default=True, help_text="Receive important updates by email."
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_in_app",
            field=models.BooleanField(
                default=True, help_text="Show in-app notifications for updates."
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="share_activity",
            field=models.BooleanField(
                default=True,
                help_text="Allow your activity (e.g. course completions) to appear in feeds and dashboards.",
            ),
        ),
    ]
