# Generated by Django 6.0.2 on 2026-03-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_notify_email_user_notify_in_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe_course_updates',
            field=models.BooleanField(default=True, help_text='Receive course updates and up-to-date info by email (e.g. new materials, announcements).'),
        ),
    ]
