# Generated by Django 4.2.27 on 2026-03-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_alter_enrolment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="hero_image_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
