# Generated by Django 6.0.2 on 2026-03-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_add_language_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('LANGUAGES', 'Languages'), ('AI', 'AI'), ('CYBER', 'Cyber Security'), ('DATA', 'Data Analysis'), ('WEB', 'Web Development'), ('OTHER', 'Other')], default='OTHER', help_text='Course category for browsing.', max_length=20),
        ),
    ]
