# Generated by Django 6.0.2 on 2026-03-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_add_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_general',
            field=models.BooleanField(default=False, help_text='If True, this is the General announcement room; all authenticated users can join.'),
        ),
    ]
