# Generated by Django 6.0.2 on 2026-03-05 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_create_general_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(help_text='YouTube or video URL.')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower first).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_videos', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, help_text='Leave empty for global/platform-wide videos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_resources', to='courses.course')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
