# Generated by Django 6.0.2 on 2026-03-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusupdate',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file or image attached to this update.', null=True, upload_to='status_attachments/%Y/%m/'),
        ),
    ]
