from django import forms

from .models import Course, CourseMaterial, Feedback, VideoResource, StudentSubmission


class CourseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Show duration in hours in the UI, backed by minutes in the DB.
        if self.instance and self.instance.pk and self.instance.duration_minutes:
            self.fields['duration_minutes'].initial = self.instance.duration_minutes / 60
        # Allow using model defaults when these are left blank in the form.
        for fname in ('capacity_type', 'delivery_mode', 'language'):
            if fname in self.fields:
                self.fields[fname].required = False

    def clean_duration_minutes(self):
        hours = self.cleaned_data.get('duration_minutes')
        if hours is None:
            return None
        try:
            hours_float = float(hours)
        except (TypeError, ValueError):
            raise forms.ValidationError('Duration must be a number.')
        if hours_float < 0:
            raise forms.ValidationError('Duration cannot be negative.')
        return int(hours_float * 60)

    class Meta:
        model = Course
        fields = [
            'title',
            'description',
            'hero_image',
            'start_datetime',
            'end_datetime',
            'duration_minutes',
            'cost',
            'capacity_type',
            'delivery_mode',
            'language',
            'category',
        ]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
            'hero_image': forms.FileInput(attrs={'class': 'form-control form-control-sm', 'style': 'max-width: 12rem;'}),
            'start_datetime': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'end_datetime': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'duration_minutes': forms.NumberInput(attrs={'class': 'form-control', 'min': 0, 'step': 1}),
            'cost': forms.NumberInput(attrs={'class': 'form-control', 'min': 0, 'step': '0.01'}),
            'capacity_type': forms.Select(attrs={'class': 'form-select'}),
            'delivery_mode': forms.Select(attrs={'class': 'form-select'}),
            'language': forms.Select(attrs={'class': 'form-select'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
        }


class CourseMaterialForm(forms.ModelForm):
    class Meta:
        model = CourseMaterial
        fields = ['title', 'file']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            # Simple file input (no autogenerated "clear" checkbox)
            'file': forms.FileInput(attrs={'class': 'form-control'}),
        }


class StudentSubmissionForm(forms.ModelForm):
    class Meta:
        model = StudentSubmission
        fields = ['title', 'file']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'file': forms.FileInput(attrs={'class': 'form-control'}),
        }


class FeedbackForm(forms.ModelForm):
    rating = forms.TypedChoiceField(
        choices=[(i, f'{i} — {"Excellent" if i == 5 else "Very Good" if i == 4 else "Good" if i == 3 else "Fair" if i == 2 else "Poor"}') for i in range(1, 6)],
        coerce=int,
        widget=forms.Select(attrs={'class': 'form-select'}),
    )

    class Meta:
        model = Feedback
        fields = ['rating', 'comment']
        widgets = {
            'comment': forms.Textarea(attrs={
                'rows': 3,
                'class': 'form-control',
                'placeholder': 'Share your experience...',
            }),
        }


class VideoResourceForm(forms.ModelForm):
    class Meta:
        model = VideoResource
        fields = ['title', 'url', 'description', 'course']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Video title'}),
            'url': forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'https://www.youtube.com/watch?v=...'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 2, 'placeholder': 'Optional description'}),
            'course': forms.Select(attrs={'class': 'form-select'}),
        }
